In [2]:
import torch
import numpy as np

In [3]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [4]:
# Addition 
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [5]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [6]:
# Subtraction 
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [7]:
# Subtraction Longhand
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [8]:
# Multiplication 
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [9]:
# Multiplication Longhand
torch.mul(tensor_b, tensor_a)

tensor([ 5, 12, 21, 32])

In [10]:
# Division 
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [11]:
# Division Longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [14]:
# Remainders Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [15]:
# Remainders Modulus Longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [16]:
# Exponents / power
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [17]:
# Exponents/Power Longhand
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [18]:
# Another way to write the longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [19]:
tensor_a

tensor([1, 2, 3, 4])

In [20]:
# Reassignment_
tensor_a.add_(tensor_b)
tensor_a

tensor([ 6,  8, 10, 12])