In [1]:
import torch

In [2]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Reshape and View

In [3]:
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

# We can do reshape if we dont know the exact number of items

In [12]:
my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
my_torch2 = my_torch2.reshape(3, -1)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [14]:
my_torch3 = torch.arange(10)
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
#! Difference between view and reshape is that view is need contiguous tensor, reshape doing the shaping by creating a copy, it doesnt need a contiguous tensor

In [22]:
# with reshape adn view they are updates
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
my_torch6 = my_torch5.reshape(2, 5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [24]:
my_torch5[1] = 21
my_torch6

tensor([[ 0, 21,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

In [34]:
my_torch7 = torch.arange(10)
my_torch7 = my_torch7.reshape(5,2)

In [37]:
my_torch7[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])