## A torch. Tensor is a multi-dimensional matrix containing elements of a single data type.
### Similar To Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPUs).
• default data type of float32.   (default data type in numpy is float64)

• More suitable for deep learning than a numpy array.

In [8]:
import numpy as np
import torch

# LIST

In [10]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# Numpy Array

In [13]:
np1 = np.random.rand(3, 2)
np1

array([[0.89603079, 0.1939602 ],
       [0.68369581, 0.88949215],
       [0.06822261, 0.02195309]])

In [15]:
np1.dtype
#! dtype is float64

dtype('float64')

# Tensor

In [16]:
tensor_2d = torch.randn(3, 2)
tensor_2d

tensor([[ 1.2086, -0.2138],
        [ 0.1131,  1.0782],
        [-0.3848, -1.7740]])

In [18]:
tensor_2d.dtype
#! dtype is float32

torch.float32

In [19]:
tensor_3d = torch.randn(2,3,5)
tensor_3d

tensor([[[ 0.0988,  0.2700, -0.4737,  1.3582, -0.9065],
         [-0.6752,  1.2740,  0.7628,  0.7882,  0.0710],
         [-0.2230, -1.6775, -1.1454, -0.5203, -0.2908]],

        [[ 0.0154, -0.7348,  0.5258,  1.7225, -0.4798],
         [-0.4534,  0.4686,  0.3083, -0.2448, -0.2651],
         [-0.9949,  0.2957,  0.5265,  0.8667,  0.5428]]])

In [20]:
## Create a tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.8960, 0.1940],
        [0.6837, 0.8895],
        [0.0682, 0.0220]], dtype=torch.float64)

# Differences between float32 & float64
### float64 -> higher precision but uses more memory and its slow for dl
### float32 -> lower precision but uses less memory and is usually better and fater for dl
## Neural networks usually dont need float64 precision 